/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/courses`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/components/DrawingCanvas`; params?: Router.UnknownInputParams; } | { pathname: `/components/MCQOptions`; params?: Router.UnknownInputParams; } | { pathname: `/components/MarkdownRenderer`; params?: Router.UnknownInputParams; } | { pathname: `/components/Sidebar`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/canvas/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/courses`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/components/DrawingCanvas`; params?: Router.UnknownOutputParams; } | { pathname: `/components/MCQOptions`; params?: Router.UnknownOutputParams; } | { pathname: `/components/MarkdownRenderer`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Sidebar`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/canvas/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/courses${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `/components/DrawingCanvas${`?${string}` | `#${string}` | ''}` | `/components/MCQOptions${`?${string}` | `#${string}` | ''}` | `/components/MarkdownRenderer${`?${string}` | `#${string}` | ''}` | `/components/Sidebar${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/courses`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/components/DrawingCanvas`; params?: Router.UnknownInputParams; } | { pathname: `/components/MCQOptions`; params?: Router.UnknownInputParams; } | { pathname: `/components/MarkdownRenderer`; params?: Router.UnknownInputParams; } | { pathname: `/components/Sidebar`; params?: Router.UnknownInputParams; } | `/+not-found` | `/canvas/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/canvas/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
